/**
 * markdown.js – Markdown exporter
 * Consumes ProcessedConversation from the preprocessing pipeline.
 * Uses pure GFM markdown — no inline HTML — for maximum compatibility
 * across VS Code, GitHub, Obsidian, Typora, and other renderers.
 */

import { stripInline } from '../pipeline/preprocess.js';

/**
 * Convert a ProcessedConversation to a GFM Markdown string.
 * @param {ProcessedConversation} processed
 */
export function toMarkdown(processed) {
    const { title, site, exportedAt, stats, messages } = processed;
    const date = new Date(exportedAt).toLocaleDateString('en-US', {
        weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
    });

    const lines = [];

    // ── Header ────────────────────────────────────────────────────────────────
    lines.push(`# ${title}`);
    lines.push(``);
    lines.push(`> **${site} Conversation Export** · Exported ${date}`);
    lines.push(``);
    lines.push(`---`);
    lines.push(``);

    // ── Overview ──────────────────────────────────────────────────────────────
    lines.push(`## Overview`);
    lines.push(``);
    lines.push(`| Stat | Value |`);
    lines.push(`|:-----|:------|`);
    lines.push(`| Platform | ${site} |`);
    lines.push(`| Exported | ${date} |`);
    lines.push(`| Total Messages | ${stats.messageCount} |`);
    lines.push(`| Your Messages | ${stats.userMessages} |`);
    lines.push(`| ${site}'s Messages | ${stats.assistantMessages} |`);
    lines.push(`| Total Words | ${stats.totalWords.toLocaleString()} |`);
    lines.push(`| Avg. Words / Message | ${stats.avgWordsPerMessage} |`);
    if (stats.codeLanguages.length > 0) {
        lines.push(`| Code Languages | ${stats.codeLanguages.join(', ')} |`);
    }
    lines.push(``);
    lines.push(`---`);
    lines.push(``);

    // ── Messages ──────────────────────────────────────────────────────────────
    lines.push(`## Messages`);
    lines.push(``);

    for (const msg of messages) {
        const { role, markdown, index, wordCount, hasCode, codeLanguages, hasTable } = msg;
        const isUser = role === 'user';
        const msgNum = index + 1;

        // Build inline metadata
        const metaParts = [`${wordCount} words`];
        if (hasCode && codeLanguages.length > 0) metaParts.push(`code: ${codeLanguages.join(', ')}`);
        if (hasTable) metaParts.push(`table`);

        const speaker = isUser ? `You` : site;
        // Pure markdown heading — no HTML tags
        lines.push(`### ${speaker} — #${msgNum} · ${metaParts.join(' · ')}`);
        lines.push(``);

        // Wrap long AI responses in a collapsible block
        if (!isUser && wordCount > 300) {
            lines.push(`> **[${wordCount} words — scroll to read]**`);
            lines.push(``);
        }

        lines.push(markdown);
        lines.push(``);
        lines.push(`---`);
        lines.push(``);
    }

    // ── Footer ────────────────────────────────────────────────────────────────
    lines.push(`*Exported from ${site} · ${date}*`);
    lines.push(``);
    lines.push(`*Generated by [MD-Export](https://github.com/YadneshTeli/MD-Export)*`);

    return lines.join('\n').trim();
}

export function downloadMarkdown(markdown, filename) {
    const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    chrome.downloads.download({ url, filename, saveAs: false }, () => {
        URL.revokeObjectURL(url);
    });
}
